### ISSUE TITLE
Run Time and Comparison

### ISSUE THREAD

**Issue by RoyiAvital** [YuanhaoGong/CurvatureFilter#1]
Could you add run time data on HD images?
How is it compared to the Bilateral Filter?

Thank You,

**Comment by YuanhaoGong** [comment]
Hi,
Thanks a lot for the comment!

Yes, I will add the running time for these filters soon. You can find the result comparison at the end of chapter six in my PhD thesis. In short, these filters are better than Bilateral Filter and Guided Filter in  terms of quality and running time.

**Comment by RoyiAvital** [comment]
Hi,
I will look at the Thesis, yet on the PDF of Presentations it seems to add some artifacts.

See page 40 of the rock.  
There are few green spots which aren't on the original image.

When you say it is superior to the Guided Filter / Bilateral Filter, in what sense do you mean?

Thank You.

**Comment by YuanhaoGong** [comment]
Thanks for letting me know!

It is true that the rock image has some artifacts. This is because we
perform these filters on RGB channel separately. If they worked in HSV
space, these artifacts would be gone.

There are two aspects when I said "better". First, our filters are derived
from variational models and differential geometry. They are theoretically
more solid than Guided filter and bilateral filter, for which there is no
mathematical models. Second, our filters are computational faster than
guided filter because we introduce the geometry instead of doing regression.

These filters are the perfect link between filters and variational models.
Before my thesis, they are considered two different things. Now, they are
linked. And these filters are the key to link them.

I have a lot of application for these filters and I put the ideas under the
Apps folder. If you are interested, you could implement some of these
applications and compare them with traditional solvers. Then you will feel
the power of these filters: general (solve arbitrary imaging models), fast
(usually two order of magnitude), simple (implementation is supper simple)
and convergence guaranteed (solid theory).

Best,
Yuanhao Gong

---

Research Fellow at National University of Singapore

PhD, ETH Zurich, Switzerland
M.S., Xiamen University, China

## B.S., Tsinghua University, China

**Comment by RoyiAvital** [comment]
Hi,

I can help with MATLAB implementation, yet not C / C++.

If you could create a documentation which links how to use this filters for Deblurring / Super Resolution / Inpainiting I will be happy to help.
I understand how this filter can assist with smoothing, yet how can you Deblur using it?
Or do you mean Deblurring just by applying "Unsharp Mask"?
How about interpolation, as you need the value of the pixel you're trying to interpolate...

Let's make a PDF with the Math how to do so and I will gladly assist you.

I will also go through the MATLAB implementation, I might be able to optimize it farther.

**Comment by YuanhaoGong** [comment]
Hi,

Do you know variational models? For example, mean curvature based image
registration can be found at
http://www.advancesindifferenceequations.com/content/2012/1/193

Just simply using my MC filter to minimize the energy functional mentioned
in above paper, you will get significant speed up.

You can check Section 6.5 in my thesis. It explains how to use these
filters for general variaitonal models.

I used Matlab a lot in the past few years. Even though I did not optimize
my Matlab implementation, I believe they are fast. Let me know if you could
make them faster :)

Best,
Yuanhao Gong

---

Research Fellow at National University of Singapore

PhD, ETH Zurich, Switzerland
M.S., Xiamen University, China

## B.S., Tsinghua University, China

**Comment by RoyiAvital** [comment]
Hello,
I'm familiar with the concept.
I wasn't sure about how you implement the math model into the usages you mentioned.

I will give you MATLAB code a try and hopefully I will be able to speed things up.

**Comment by YuanhaoGong** [comment]
Cool! Let me know if it works! Cheers!

Best,
Yuanhao Gong

---

Research Fellow at National University of Singapore

PhD, ETH Zurich, Switzerland
M.S., Xiamen University, China

## B.S., Tsinghua University, China

**Comment by YuanhaoGong** [comment]
Hi there,

You’ve been invited by Yuanhao to join the Dropbox Campus Cup! Campus Cup lets you team up with your classmates to earn up to 25 GB of free Dropbox space for two years!

To earn space, just invite friends and use Dropbox to share, collaborate, and get work done.

Join Campus Cup![2](https://www.dropbox.com/l/prL84h5JVnjY6sVhL0GUhJ/campuscup?text=1)

Note that you must be a student currently enrolled at a higher education institution in order to participate. Learn more about Campus Cup.[3](https://www.dropbox.com/l/jq8KOkb1qtOqLuKzeABMHt/help/9131?text=1)

Happy Dropboxing!

 Work together, win together. 

---

If you prefer not to receive invites from Dropbox, please go here[4](https://www.dropbox.com/l/P1tMuWfCoUWE51FdYmzIUl?text=1).
Dropbox, Inc., PO Box 77767, San Francisco, CA 94107
